# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import warehouse_pb2 as warehouse__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in warehouse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WarehouseStub:
    """Опис сервісу складу та його методів
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStock = channel.unary_unary(
                '/warehouse.Warehouse/CheckStock',
                request_serializer=warehouse__pb2.StockRequest.SerializeToString,
                response_deserializer=warehouse__pb2.StockResponse.FromString,
                _registered_method=True)
        self.ReserveStock = channel.unary_unary(
                '/warehouse.Warehouse/ReserveStock',
                request_serializer=warehouse__pb2.ReserveRequest.SerializeToString,
                response_deserializer=warehouse__pb2.ReserveResponse.FromString,
                _registered_method=True)


class WarehouseServicer:
    """Опис сервісу складу та його методів
    """

    def CheckStock(self, request, context):
        """Метод для перевірки наявності товару
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Метод для резервування (списання) товару
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=warehouse__pb2.StockRequest.FromString,
                    response_serializer=warehouse__pb2.StockResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=warehouse__pb2.ReserveRequest.FromString,
                    response_serializer=warehouse__pb2.ReserveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warehouse.Warehouse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('warehouse.Warehouse', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Warehouse:
    """Опис сервісу складу та його методів
    """

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.Warehouse/CheckStock',
            warehouse__pb2.StockRequest.SerializeToString,
            warehouse__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.Warehouse/ReserveStock',
            warehouse__pb2.ReserveRequest.SerializeToString,
            warehouse__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
