# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\"\"\n\x0cStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"X\n\rStockResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x12\x15\n\rcurrent_stock\x18\x02 \x01(\x05\x12\x1a\n\x12warehouse_location\x18\x03 \x01(\t\"6\n\x0eReserveRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x0fReserveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x93\x01\n\tWarehouse\x12?\n\nCheckStock\x12\x17.warehouse.StockRequest\x1a\x18.warehouse.StockResponse\x12\x45\n\x0cReserveStock\x12\x19.warehouse.ReserveRequest\x1a\x1a.warehouse.ReserveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=30
  _globals['_STOCKREQUEST']._serialized_end=64
  _globals['_STOCKRESPONSE']._serialized_start=66
  _globals['_STOCKRESPONSE']._serialized_end=154
  _globals['_RESERVEREQUEST']._serialized_start=156
  _globals['_RESERVEREQUEST']._serialized_end=210
  _globals['_RESERVERESPONSE']._serialized_start=212
  _globals['_RESERVERESPONSE']._serialized_end=263
  _globals['_WAREHOUSE']._serialized_start=266
  _globals['_WAREHOUSE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
